SRC_FILE    = \
        problem.F90 \
        matrices.F90 \
        DPGLaser.F \
            set_initial_mesh.F90 \
	    celem.F90 \
            elem.F90 \
            dirichlet.F90 \
	    exact.F90 \
	    fake.F90 \
	    finalize.F90 \
	    getf.F90 \
            initialize.F90 \
            main.F90 \
	    set_mesh_refinement.F90 \
	    soldis.F90 \
            my_tests.F \
        compute_BC_interp_error.F








